# Generated by Django 3.2.4 on 2025-01-24 11:43

from django.db import migrations, models
import imageit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_photo', imageit.models.ScaleItImageField(upload_to='')),
                ('crop_it_photo', imageit.models.CropItImageField(upload_to='')),
            ],
        ),
    ]
